# Generated by Django 2.2.3 on 2019-07-13 13:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mgrtests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9dbea28e-a65c-499b-8ad6-d03624da8739'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='id',
            field=models.UUIDField(default=uuid.UUID('18459d07-d31e-40e8-b7aa-dba34e8af636'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='testruns',
            name='id',
            field=models.UUIDField(default=uuid.UUID('edc77f43-5c46-4deb-b627-840fcf4bd7dd'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testruns',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3eed845a-1590-4934-88f2-3d3e0957aa8f'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='testsuite',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='version',
            name='id',
            field=models.UUIDField(default=uuid.UUID('1f01cd83-ce71-4d17-91d7-dac5201308aa'), primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='version',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
